name: CI

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      
      - name: install dependencies
        run: python -m pip install -r requirements.txt
      
      - name: run unit test
        run: python -m pytest /app.py

  docker:
    needs: unit-test

    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -t user-service:${{ github.sha }} .
     
      - name: show docker image
        run: docker images user-service

      - name: run docker container
        run: |
          docker run \
            -d -p 8080:8080 \
              --name user-service \
                user-service:${{ github.sha }}

      - name: test container
        run: curl http://localhost:8080/health